#' pyRAM transmission loss, Kerguelen2015 summer, 25 Hz
#'
#' Transmission loss computed with pyRAM (parabolic equation model) on
#' GLORYS12V1 sound speed profiles, along 24 radial transects out to 1000 km,
#' for the South Kerguelen Plateau (SKP) mooring site. Used by the
#' `noiseLevels` article to demonstrate `pDetGivenNL` against real propagation
#' physics rather than spherical spreading.
#'
#' Eight of the 24 transects hit land or leave the modelled bathymetry well
#' before 1000 km (see [kerguelen2015TLmeta]). Rows beyond a given transect's
#' `TruncationDistance_m` describe whatever pyRAM computed past that point,
#' not open-water propagation, and should not be used without masking via
#' `truncationDistance`.
#'
#' @format A data.frame with 10,000 rows and 25 columns:
#' \describe{
#'   \item{range_m}{Range in metres, 100 to 1,000,000 in 100 m steps.}
#'   \item{tl000, tl015, ..., tl345}{Transmission loss in dB at that range,
#'     one column per transect, named by azimuth in degrees.}
#' }
#'
#' @source `S:/manuscripts/2026-CopernicusPyRAM/data/output/TL_Kerguelen2015_combined_25hz_GLORYS12_summer_25Hz.csv`,
#'   generated by the `BrianSMiller/2026-CopernicusPyRAM` pipeline. Bundled
#'   with [kerguelen2015TLmeta] in `data/kerguelen2015pyram.rda`; rebuild both
#'   via `data-raw/kerguelen2015pyram.R`.
"kerguelen2015TL"


#' Transect metadata for the Kerguelen2015 pyRAM transmission loss table
#'
#' One row per transect in [kerguelen2015TL], giving the azimuth, source
#' location, and the range at which that transect's bathymetry
#' (`cmems_mod_glo_phy_my_0.083deg_static`) runs onto land. This is a
#' different bathymetry product from whatever the AWR manuscript's own
#' AcTUP/WOA18-based `cde()` calls use, so it finds a different coastline and
#' cannot be substituted for that pipeline's own truncation vector, or vice
#' versa.
#'
#' Build the truncation vector for [kerguelen2015TL] by matching on azimuth,
#' not row position:
#'
#' ```r
#' transectAz <- as.numeric(sub("^tl", "", names(kerguelen2015TL)[-1]))
#' trunc      <- kerguelen2015TLmeta$TruncationDistance_m[
#'                 match(transectAz, kerguelen2015TLmeta$azimuths)]
#' ```
#'
#' @format A data.frame with 24 rows, one per transect:
#' \describe{
#'   \item{azimuths}{Transect bearing, degrees, 0 to 345 in 15 degree steps.}
#'   \item{lonStart, latStart}{Source location (WGS84).}
#'   \item{TruncationDistance_m}{Range in metres at which this transect
#'     leaves the modelled bathymetry. 1,000,000 where the full 1000 km
#'     transect stays in water.}
#'   \item{freq_hz, zr_m, call_type, site, season, year}{Simulation
#'     parameters: 25 Hz, 20 m receiver depth, combined ABW/fin call type,
#'     Kerguelen2015, summer 2015.}
#'   \item{ssp_source, bathy_source}{GLORYS12V1 and the static CMEMS
#'     bathymetry product used for the land mask.}
#' }
#'
#' @source `S:/manuscripts/2026-CopernicusPyRAM/data/output/metadata/TL_Kerguelen2015_combined_25hz_GLORYS12_summer_25Hz_metadata.csv`.
#'   Bundled with [kerguelen2015TL] in `data/kerguelen2015pyram.rda`; rebuild
#'   both via `data-raw/kerguelen2015pyram.R`.
"kerguelen2015TLmeta"
